export const LoadingLicense = [
    {
        id: "Carregando...",
        area: "Carregando...",
        unidade: "Carregando...",
        sub_unidade: "Carregando...",
        data_requerimento: "Carregando...",
        controle: "Carregando...",
        orgao_emissor: "Carregando...",
        tipo: "Carregando...",
        especificacao: "Carregando...",
        numero_licenca: "Carregando...",
        fcei_sinfat: "Carregando...",
        num_processo_sinfat: "Carregando...",
        sgpe: "Carregando...",
        num_processo_sei: "Carregando...",
        data_emissao: "Carregando...",
        data_vencimento: "Carregando...",
        previsao: "Carregando...",
        requerimento: "Carregando...",
        data_protocolo_orgao: "Carregando...",
        emitida_nova_licenca: "Carregando...",
        situacao_processo: "Carregando...",
        atualizado_sa: "Carregando...",
        observacoes: "Carregando...",
        providenciar_doc: "Carregando...",
        datalimite: "Carregando...",
        tempo_tramitacao: "Carregando...",
        situacao_licenca: "Carregando...",
        setor_responsavel: "Carregando...",
        dias_para_vencer: "Carregando...",
        button: "Carregando...",
    },
];
